### ISSUE TITLE
Nutzung für Contao 3.2 oder neuer

### ISSUE THREAD

**Issue by macjag** [aschempp/contao-dashboard#4]
Hallo, gibt es eine neuere Version bzw. ist es geplant für z.B. Contao 3.2 oder neuer? 
Vielen Dank im Voraus.
Macjag

**Comment by aschempp** [comment]
@qzminski would it be difficult to update this extension?

**Comment by qzminski** [comment]
I think it should be pretty easy.

**Comment by aschempp** [comment]
Then please do that :-)
We can create a new minor version for 3.2+ only.

**Comment by qzminski** [comment]
New version available.

**Comment by aschempp** [comment]
Did you publish the new version to ER? ;-)

**Comment by laufhannes** [comment]
There is no current version in the ER.
I'm glad I found it here - it's exactly what I was searching for to leave some hints for my customers.

**Comment by aschempp** [comment]
@qzminski can I release a new version? What would be the compatibility? 3.2 and 3.3?

**Comment by qzminski** [comment]
I think you can release it with 3.2 and 3.3. We'll fix issues if there's any problem 8)

**Comment by ways2web** [comment]
the Option "Erzwingen" doesnt work. No Mediabox in Contao 3 Backend.
